### ISSUE TITLE
Failed to change a PO Line from Physical to Electronic

### ISSUE THREAD

**Issue by DianaUV** [liron58/Cloud-App-switch-po-type#1]
Hello,
When trying to convert a PO Line from Physical to Electronic in the cloud app, I get the following error message: `“Failed to transform. Cannot add PO Line to PO that has already been sent”`

![imagen](https://user-images.githubusercontent.com/82812066/115224606-5bb27180-a10d-11eb-8a2a-c31e7fa5b353.png)

It's a physical PO Line that has already been sent. We have some like this coming from our migration into Alma from Millennium. Now we would like to change them from Physical to Electronic, but the app shows the error message. We are doing in Sandbox.

Is it possible to change **a sent PO Line** from Physical to Electronic in the cloud app?
We don’t know what is the problem. Can you help us?
I have post a message on Ex Libris developer forum.
Thank you.
All the best,

Diana

**Comment by ori229** [comment]
See https://developers.exlibrisgroup.com/forums/topic/switch-po-line-type/
