### ISSUE TITLE
Starting server failed

### ISSUE THREAD

**Issue by hagbeck** [liron58/Cloud-App-switch-po-type#2]
Hello,

I'm trying to start the server an getting the following error:

> up to date, audited 1646 packages in 7s
>
> 144 packages are looking for funding
>  run `npm fund` for details
>
> 12 vulnerabilities (5 moderate, 7 high)
>
> To address all issues (including breaking changes), run:
>  npm audit fix --force
>
> Run `npm audit` for details.
>
> Using config:
> {
>  env: ...,
>  port: 4201
> }
>
> ⠙ Starting server...An unhandled exception occurred: Cannot find module 'typescript'
> Require stack:
> - ./alma-cloud-apps/Cloud-App-switch-po-type/node_modules/@angular-devkit/build-angular/src/webpack/utils/helpers.js
> - ./alma-cloud-apps/Cloud-App-switch-po-type/node_modules/@angular-devkit/build-angular/src/utils/package-chunk-sort.js
> - ./alma-cloud-apps/Cloud-App-switch-po-type/node_modules/@angular-devkit/build-angular/src/builders/dev-server/index.js
> - ./alma-cloud-apps/Cloud-App-switch-po-type/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
> - ./alma-cloud-apps/Cloud-App-switch-po-type/node_modules/@angular-devkit/architect/node/index.js
> - ./alma-cloud-apps/Cloud-App-switch-po-type/node_modules/@angular/cli/models/architect-command.js
> - ./alma-cloud-apps/Cloud-App-switch-po-type/node_modules/@angular/cli/commands/serve-impl.js
> - ./alma-cloud-apps/Cloud-App-switch-po-type/node_modules/@angular-devkit/schematics/tools/export-ref.js
> - ./alma-cloud-apps/Cloud-App-switch-po-type/node_modules/@angular-devkit/schematics/tools/index.js
> - ./alma-cloud-apps/Cloud-App-switch-po-type/node_modules/@angular/cli/utilities/json-schema.js
> - ./alma-cloud-apps/Cloud-App-switch-po-type/node_modules/@angular/cli/models/command-runner.js
> - ./alma-cloud-apps/Cloud-App-switch-po-type/node_modules/@angular/cli/lib/cli/index.js
> - ./alma-cloud-apps/Cloud-App-switch-po-type/node_modules/@angular/cli/lib/init.js
> - ./alma-cloud-apps/Cloud-App-switch-po-type/node_modules/@angular/cli/bin/ng
> See "/tmp/ng-UgRRcu/angular-errors.log" for further details.

I'm using 

* node v16.14.0
* npm 8.5.5

A few weeks ago the server starts and the was usable in the Sandbox.

**Comment by mgobat** [comment]
@hagbeck, is there a "typescript" directory in your ./alma-cloud-apps/Cloud-App-switch-po-type/node_modules directory?

**Comment by hagbeck** [comment]
No, there is not.

**Comment by mgobat** [comment]
Try issuing the "npm install" command from your ./alma-cloud-apps/Cloud-App-switch-po-type directory, then check again.

**Comment by hagbeck** [comment]
I'm getting the following output 

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/architect@0.1102.19',
npm WARN EBADENGINE   required: { node: '>= 10.13.0', npm: '^6.11.0 || ^7.5.6', yarn: '>= 1.13.0' },
npm WARN EBADENGINE   current: { node: 'v16.14.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/build-optimizer@0.1102.19',
npm WARN EBADENGINE   required: { node: '>= 10.13.0', npm: '^6.11.0 || ^7.5.6', yarn: '>= 1.13.0' },
npm WARN EBADENGINE   current: { node: 'v16.14.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/build-webpack@0.1102.19',
npm WARN EBADENGINE   required: { node: '>= 10.13.0', npm: '^6.11.0 || ^7.5.6', yarn: '>= 1.13.0' },
npm WARN EBADENGINE   current: { node: 'v16.14.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/core@11.2.19',
npm WARN EBADENGINE   required: { node: '>= 10.13.0', npm: '^6.11.0 || ^7.5.6', yarn: '>= 1.13.0' },
npm WARN EBADENGINE   current: { node: 'v16.14.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/schematics@11.2.19',
npm WARN EBADENGINE   required: { node: '>= 10.13.0', npm: '^6.11.0 || ^7.5.6', yarn: '>= 1.13.0' },
npm WARN EBADENGINE   current: { node: 'v16.14.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular/cli@11.2.19',
npm WARN EBADENGINE   required: { node: '>= 10.13.0', npm: '^6.11.0 || ^7.5.6', yarn: '>= 1.13.0' },
npm WARN EBADENGINE   current: { node: 'v16.14.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/build-angular@0.1102.19',
npm WARN EBADENGINE   required: { node: '>= 10.13.0', npm: '^6.11.0 || ^7.5.6', yarn: '>= 1.13.0' },
npm WARN EBADENGINE   current: { node: 'v16.14.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@ngtools/webpack@11.2.19',
npm WARN EBADENGINE   required: { node: '>= 10.13.0', npm: '^6.11.0 || ^7.5.6', yarn: '>= 1.13.0' },
npm WARN EBADENGINE   current: { node: 'v16.14.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@schematics/angular@11.2.19',
npm WARN EBADENGINE   required: { node: '>= 10.13.0', npm: '^6.11.0 || ^7.5.6', yarn: '>= 1.13.0' },
npm WARN EBADENGINE   current: { node: 'v16.14.0', npm: '8.5.5' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@schematics/update@0.1102.19',
npm WARN EBADENGINE   required: { node: '>= 10.13.0', npm: '^6.11.0 || ^7.5.6', yarn: '>= 1.13.0' },
npm WARN EBADENGINE   current: { node: 'v16.14.0', npm: '8.5.5' }
npm WARN EBADENGINE }

up to date, audited 1646 packages in 6s

144 packages are looking for funding
  run `npm fund` for details

12 vulnerabilities (5 moderate, 7 high)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```
and the same error.

**Comment by hagbeck** [comment]
A few weeks ago the files package.json and package-lock.json were modified. 
I've rolled them back now to the master-version of the repository and now the server starts successfully after a while.

**Comment by mgobat** [comment]
@hagbeck, great!  Glad you overcame that roadblock. Good luck!
